Add load balancer exercises
cloudscale-ch/cloud-exercises pull request #2
Opened 2024-06-05 07:42 UTC by href

2024-09-01 19:11 UTC, subsecond commented on README.md
> +Modern deployments in general, and Kubernetes deployments in particluar, often employ load balancers to distribute load, improve uptime, and to increase security.
Please get rid of the last "to".

2024-09-01 19:12 UTC, subsecond commented on exercises/06-load-balancers.md
> +Modern deployments in general, and Kubernetes deployments in particluar, often employ load balancers to distribute load, improve uptime, and to increase security.
Same here: Please drop the last "to".

2024-09-01 19:14 UTC, subsecond commented on exercises/06-load-balancers.md
> +Load balancers include components, read the documentation to understand what these end-points manage:
Please change to "Load balancers consist of various components. Read..."
If "load balancer" does not have a dash, then "end points" does not have one either.

2024-09-01 19:16 UTC, subsecond commented on exercises/06-load-balancers.md
> +Using your favourite approach (Terraform, Ansible, REST), create a load-balancer that includes these servers as pool members. When queried via HTTP, the load-balancer should actually return answers f
Inconsistency: "load-balancer" without a dash everywhere else.

2024-09-01 19:17 UTC, subsecond requested changes
Sorry for the delay. Great work!

Some minor text corrections. Other than that: Ship it!

2024-09-02 06:55 UTC, href commented on exercises/06-load-balancers.md
> +Using your favourite approach (Terraform, Ansible, REST), create a load-balancer that includes these servers as pool members. When queried via HTTP, the load-balancer should actually return answers f
Done.

2024-09-02 06:56 UTC, merged